### ISSUE TITLE
Raw url encode when src is with domain prefix

### ISSUE THREAD

**Issue by qbadev** [FluidTYPO3/vhs#1511]
I have a Storage non-public. I serve images, crop and scale them. I use `<v:media.image/>`. After rendering a tag, image url is messed up, as its parts are encoded using function [rawurlencode](https://secure.php.net/manual/en/function.rawurlencode.php).
It takes place in file [Classes/ViewHelpers/Media/AbstractMediaViewHelper.php, line 61](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Media/AbstractMediaViewHelper.php#L61).

When an original image is in `fileadmin/` folder (publicly accessible), it result with correct src. But when original file is hidden from web users, url is not being checked before encoding.
I checked that output image gets domain prefix (absolute url) from Typo3 native `getImgResource` function.

I think, vhs media.image helper should check if processed image src is absolute.

**Comment by luzat** [comment]
I didn't see this one before, but this should probably be considered when looking at #1512 and #1513, too, given that URL encoding at this place seems to break in multiple cases.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/vhs/commit/9af62c4c73330e99393729cbf3d873a4307ed92c

**Comment by qbadev** [comment]
In my case, after applying a patch, still doesn't work as expected. Sample image src is: `http%3A//domain/imagePath` and browsers can't render such image. Problem seems to be still in line 61 of Your commit.
